name: Update Proxy List

on:
  push:
    branches:
      - main  # 当 main 分支有更改时触发
  schedule:
    - cron: '0 0 * * 0'  # 每周日的 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-proxy-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download proxy URLs
        id: download_urls
        run: |
          # 确保 urls 文件存在
          if [ ! -f proxy/urls ]; then
            echo "proxy/urls file not found!"
            exit 1
          fi

          # 创建一个临时文件
          temp_file=$(mktemp)

          # 读取 urls 文件并下载内容
          while IFS= read -r url; do
            echo "Downloading from $url"
            curl -s "$url" >> $temp_file
          done < proxy/urls

          # 确保 proxy 目录存在
          mkdir -p proxy

          # 将临时文件内容写入 proxy.list
          mv $temp_file proxy/proxy.list
          
      - name: Commit and push changes
        run: |
          git config --local user.email "kmcyd1@gmail.com"
          git config --local user.name "hankun"
          git add proxy/proxy.list
          git commit -m "Update proxy.list with new rules" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
